"""Reconcile the submitted checksum manifest with its frozen Git tree."""
import hashlib
import json
from pathlib import Path
import subprocess


HERE = Path(__file__).resolve().parent
PACKAGE = HERE.parent
REPO = HERE.parents[3]
PARENT = "ebe86025e7f122f0a93b841cf41211bc50b715fe"
PACKAGE_PREFIX = "research/doom/cancel_key_release_intervals_59_4d74_20261004"
GENERATED_BYTECODE = {
    "baseline/__pycache__/executor_v3.cpython-314.pyc",
    "baseline/__pycache__/input_owner_v12.cpython-314.pyc",
    "baseline/__pycache__/lease.cpython-314.pyc",
}
EXPECTED_UNMANIFESTED_TRACKED = {"AUDIT.json", "FILES.sha256"}


def verify_manifest(package, entries, tracked_paths):
    package = Path(package)
    manifest_paths = [rel for _digest, rel in entries]
    tracked_prefix = PACKAGE_PREFIX + "/"
    tracked = {
        path[len(tracked_prefix):]
        for path in tracked_paths
        if path.startswith(tracked_prefix)
    }
    errors = []
    if len(manifest_paths) != len(set(manifest_paths)):
        errors.append("duplicate manifest paths")
    if not GENERATED_BYTECODE.issubset(set(manifest_paths)):
        errors.append("expected generated-bytecode entries are absent from manifest")

    for digest, rel in entries:
        path = package / rel
        if Path(rel).is_absolute() or ".." in Path(rel).parts:
            errors.append(f"unsafe manifest path: {rel}")
            continue
        if rel in GENERATED_BYTECODE:
            if rel in tracked or path.exists():
                errors.append(f"generated bytecode unexpectedly exists/tracked: {rel}")
            continue
        if rel not in tracked:
            errors.append(f"manifest member absent from frozen Git tree: {rel}")
        if not path.is_file():
            errors.append(f"manifest member missing from checkout: {rel}")
        elif hashlib.sha256(path.read_bytes()).hexdigest() != digest:
            errors.append(f"manifest hash mismatch: {rel}")

    expected_manifest_tracked = set(manifest_paths) - GENERATED_BYTECODE
    unmanifested = tracked - set(manifest_paths)
    if tracked != expected_manifest_tracked | EXPECTED_UNMANIFESTED_TRACKED:
        errors.append("tracked package members differ from the frozen manifest scope")

    return {
        "manifest_entries": len(entries),
        "verified_tracked_entries": len(expected_manifest_tracked),
        "unmanifested_tracked_files": sorted(unmanifested),
        "missing_generated_bytecode": sorted(GENERATED_BYTECODE & set(manifest_paths)),
        "errors": errors,
        "pass": not errors,
    }


def run():
    manifest = PACKAGE / "FILES.sha256"
    entries = []
    for line in manifest.read_text(encoding="utf-8").splitlines():
        digest, rel = line.split("  ", 1)
        entries.append((digest, rel))
    listing = subprocess.run(
        ["git", "-C", str(REPO), "ls-tree", "-r", "--name-only", PARENT,
         "--", PACKAGE_PREFIX],
        check=True,
        capture_output=True,
        text=True,
    )
    tracked_paths = listing.stdout.splitlines()
    result = verify_manifest(PACKAGE, entries, tracked_paths)
    result["schema"] = "cancel-key-release-intervals-manifest-audit-v2"
    result["frozen_parent"] = PARENT
    return result


if __name__ == "__main__":
    result = run()
    print(json.dumps(result, indent=2))
    raise SystemExit(0 if result["pass"] else 1)
