import ast,contextlib,hashlib,io,json,unittest
from pathlib import Path
from types import SimpleNamespace
ROOT=Path("/src"); D=ROOT/"research/doom"; P=D/"v39_adapter_nested_identity_taint_59_a08_20261005"; BASE=P/"BASELINE_SOURCE.py"; SRC=D/"map01_overlap_controller_v39.py"; TEST=D/"test_map01_v39_typed_state_feedback.py"; FIX=D/"map01_v39_perkey_bridge_a01/results/construction-a01/candidate-events.jsonl"; OUT=Path("/out/A08_RESULT.json"); F=json.loads((P/"A08_FREEZE.json").read_text())
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
for p,k in ((BASE,"baseline_source_sha256"),(SRC,"candidate_source_sha256"),(TEST,"test_sha256"),(FIX,"fixture_sha256")): assert sha(p)==F[k],k
def load(p):
 t=ast.parse(p.read_text()); n=next(x for x in t.body if isinstance(x,ast.FunctionDef) and x.name=="input_edge_receipts"); e={"hashlib":hashlib}; exec(compile(ast.fix_missing_locations(ast.Module(body=[n],type_ignores=[])),str(p),"exec"),e); return e["input_edge_receipts"]
METHODS=("test_input_edge_receipt_rejects_duplicate_adapter_rows","test_input_edge_receipt_rejects_unknown_outer_event_with_adapter_edge","test_input_edge_receipt_rejects_legacy_transition_with_adapter_edge","test_input_edge_receipt_rejects_outer_nested_token_conflict","test_input_edge_receipt_rejects_outer_group_split_for_same_actuation","test_input_edge_receipt_taints_nested_identity_for_unavailable_outer_key_token")
def run(fn):
 t=ast.parse(TEST.read_text()); c=next(x for x in t.body if isinstance(x,ast.ClassDef) and x.name=="V39TypedStateFeedbackTests"); ns=[next(x for x in c.body if isinstance(x,ast.FunctionDef) and x.name==m) for m in METHODS]; cls=ast.ClassDef(name="A08Tests",bases=[ast.Attribute(value=ast.Name(id="unittest",ctx=ast.Load()),attr="TestCase",ctx=ast.Load())],keywords=[],body=ns,decorator_list=[]); mod=ast.Module(body=[ast.Import(names=[ast.alias(name="json")]),ast.Import(names=[ast.alias(name="unittest")]),cls],type_ignores=[]); env={"HERE":D,"controller":SimpleNamespace(input_edge_receipts=fn)}; exec(compile(ast.fix_missing_locations(mod),str(TEST),"exec"),env); stream=io.StringIO(); res=unittest.TextTestRunner(stream=stream,verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(env["A08Tests"])); return res.wasSuccessful(),stream.getvalue(),res.testsRun,len(res.failures)+len(res.errors)
bf,bo,bn,be=run(load(BASE)); cf,co,cn,ce=run(load(SRC)); events=[json.loads(x) for x in FIX.read_text().splitlines()]; down=next(x for x in events if x.get("event")=="input_admission"); up=next(x for x in events if x.get("event")=="input_release_measurement"); cases=[]
for field,value in (("intent_token",None),("intent_token",["bad"]),("key",None),("key",["bad"])):
 x=json.loads(json.dumps(down)); x[field]=value; rec=[r for r in load(BASE)([down,x,up]) if r.get("status","").startswith("adapter_edge_")]; cases.append({"field":field,"value":value,"baseline_false_pair":any(r["status"]=="adapter_edge_brackets_paired" and r["down_edge_interval_ns"] is not None and r["up_edge_interval_ns"] is not None for r in rec)})
for p in (SRC,TEST): compile(p.read_text(),str(p),"exec")
r={"experiment":"V39_ADAPTER_NESTED_IDENTITY_MALFORMED_OUTER_TAINT_A08","baseline_head":F["baseline_head"],"baseline_source_sha256":sha(BASE),"candidate_source_sha256":sha(SRC),"test_sha256":sha(TEST),"fixture_sha256":sha(FIX),"baseline":{"passed":bf,"tests":bn,"failed_tests":be,"output":bo},"candidate":{"passed":cf,"tests":cn,"failed_tests":ce,"output":co},"malformed_outer_cases":cases,"all_four_baseline_false_pairs":all(x["baseline_false_pair"] for x in cases),"syntax_compile":"PASS"}; OUT.write_text(json.dumps(r,indent=2)+"\n"); print(json.dumps({k:v for k,v in r.items() if k not in ("baseline","candidate")},indent=2)); print("BASELINE\n"+bo+"CANDIDATE\n"+co); raise SystemExit(0 if r["all_four_baseline_false_pairs"] and cf and not bf else 1)
