from __future__ import annotations
import hashlib,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent
BASE=Path(sys.argv[1]) if len(sys.argv)>1 else Path('research/live_control')
OUT=Path(sys.argv[2]) if len(sys.argv)>2 else HERE/'rebuilt'
OUT.mkdir(parents=True,exist_ok=True)
base_hashes={
 'executor_v9.py':'0eac224498d7b1dbe17a77ad05f39f6e66835120059928cb4f8c7faf731b6087',
 'cause_servo_interactive_v6.py':'c0358690c3c4043c6e01776b04afc7b7ff8a3c9ece9b626c0799fd7219cbb5e6',
 'cause_servo_socket_v8.py':'dc79236a74c253e4633ac6b92acc1776cb4b8db7853dce8e312786d7445988c2',
 'post_release_observation_v2.py':'69d2b2975d5cd0911af2952085eb481f590468d47f5e73cc0256bd3714ae1541'}
for n,h in base_hashes.items():
    got=hashlib.sha256((BASE/n).read_bytes()).hexdigest()
    if got!=h: raise SystemExit(f'base hash mismatch {n}: {got} != {h}')
for n in ['authority_ended_bridge_v2.py','post_authority_normalize_v2.py']:
    (OUT/n).write_bytes((HERE/n).read_bytes())
src=(BASE/'executor_v9.py').read_text()
src=src.replace('from post_release_observation_v2 import collect\n','from post_release_observation_v2 import collect\nfrom post_authority_normalize_v2 import normalize\n')
old="""            post_release = None\n            if (status == 'expired' or (status == 'needs_decision' and decision_reason in ('focus_changed', 'surface_changed'))) and release.get('verified') is True:\n                self.emit(dict(event='input_stopped', id=identifier, decision_reason=('expired' if status == 'expired' else decision_reason),\n                               interruption=interruption, release=release, stopped_ns=time.perf_counter_ns(),\n                               followup='two passive observations; terminal follows; no further program steps'))\n                post_release = collect(self.backend, self.emit, identifier, completed, cancel.cancel)\n            with self.lock:\n                self.emit(dict(event='terminal',id=identifier,status=status,error=error,\n                               steps_completed=completed,release=release,\n                               interruption=interruption,decision_reason=decision_reason,post_release_observation=post_release,\n                               terminal_ns=time.perf_counter_ns(),\n                               semantic_completion='program status only; task scoring is separate'))\n"""
new="""            post_release = None\n            post_authority = None\n            legacy_terminal_status = None\n            if (status == 'expired' or (status == 'needs_decision' and decision_reason in ('focus_changed', 'surface_changed'))) and release.get('verified') is True:\n                scheduled_expiry = status == 'expired'\n                release_sequence = self.backend.sequence\n                lifecycle_deadline_ns = time.perf_counter_ns() + 400_000_000 if scheduled_expiry else None\n                self.emit(dict(event='input_stopped', id=identifier, decision_reason=('expired' if scheduled_expiry else decision_reason),\n                               interruption=interruption, release=release, stopped_ns=time.perf_counter_ns(),\n                               followup='two passive observations; terminal follows; no further program steps'))\n                post_release = collect(self.backend, self.emit, identifier, completed, cancel.cancel)\n                if scheduled_expiry:\n                    finished_ns = time.perf_counter_ns()\n                    post_authority = normalize(post_release, release_sequence=release_sequence,\n                                               lifecycle_deadline_ns=lifecycle_deadline_ns,\n                                               snapshot_finished_ns=finished_ns)\n                    legacy_terminal_status = 'expired'\n                    status = 'authority_ended'\n            with self.lock:\n                self.emit(dict(event='terminal',id=identifier,status=status,error=error,\n                               steps_completed=completed,release=release,\n                               interruption=interruption,decision_reason=decision_reason,post_release_observation=post_release,\n                               post_authority_observation=post_authority,legacy_terminal_status=legacy_terminal_status,\n                               terminal_ns=time.perf_counter_ns(),\n                               semantic_completion='program status only; task scoring is separate'))\n"""
if old not in src: raise SystemExit('executor pattern not found')
src=src.replace(old,new);(OUT/'executor_v10_authority_ended_v2.py').write_text(src)
src=(BASE/'cause_servo_interactive_v6.py').read_text()
src=src.replace('import argparse,contextlib,hashlib,json,shutil,sys,threading,time','import argparse,contextlib,hashlib,json,os,shutil,sys,threading,time')
src=src.replace('from executor_v9 import Executor','from executor_v10_authority_ended_v2 import Executor')
src=src.replace("HERE=Path(__file__).resolve().parent\n", "HERE=Path(__file__).resolve().parent\nBASE=Path(os.environ.get('AGENT_INTERFACE_LIVE_CONTROL_BASE', HERE))\n")
start=src.index("        hashes={}\n        for path in [")
end=src.index("        suite.write_json(args.out/'sources.json',hashes)\n",start)+len("        suite.write_json(args.out/'sources.json',hashes)\n")
block="""        hashes={}\n        candidate_paths=[HERE/'cause_servo_interactive_v7.py',HERE/'executor_v10_authority_ended_v2.py',HERE/'post_authority_normalize_v2.py',HERE/'authority_ended_bridge_v2.py']\n        base_paths=[BASE/n for n in ['rejection_identity_v1.py','cause_servo_session_v1.py','cause_session_v1.py','session_v21.py','patch_servo_v5.py','visual_anchor_v2.py','visual_anchor_v3.py','visual_anchor_v4.py','post_release_observation_v2.py','lease_cause_v1.py','lease_cause_v2.py','input_owner_v10.py','session_v16.py','patch_servo.py','visual_anchor.py','session_v15.py','session_v13.py','session_v12.py','session_v11.py','input_owner_v9.py','pointer_reply_v2.py','session_v9.py','input_owner_v5.py','presentation.py','session_v8.py','quiet_window.py','session_v7.py','session_v6.py','input_owner_v2.py','session_v5.py','input_owner.py','executor_v3.py','session_v4.py','lease.py']]\n        shared_paths=[BASE.parent/'observation_tiles/tile_transport.py',BASE.parent/'observation_tiles/image_artifact.py',BASE.parent/'observation_gating/gui_suite.py',BASE.parent/'observation_gating/exact_gate.py',BASE.parent/'real_apps_v1/real_app_suite_v1.py']\n        for path in candidate_paths:\n            hashes['candidate/'+path.name]=hashlib.sha256(path.read_bytes()).hexdigest()\n        for path in base_paths+shared_paths:\n            hashes[str(path.relative_to(BASE.parent))]=hashlib.sha256(path.read_bytes()).hexdigest()\n        suite.write_json(args.out/'sources.json',hashes)\n"""
src=src[:start]+block+src[end:];(OUT/'cause_servo_interactive_v7.py').write_text(src)
sock=(BASE/'cause_servo_socket_v8.py').read_text().replace("HERE/'cause_servo_interactive_v6.py'","HERE/'cause_servo_interactive_v7.py'")
(OUT/'cause_servo_socket_v9.py').write_text(sock)
expected={'authority_ended_bridge_v2.py':'37e6551baedaddad50ca8ef64677e3c387f742875ad3e28fa6ea630e58ad7d51','post_authority_normalize_v2.py':'dc98340c5434160684802a92f04d96f47420bf908198f8861b2148cbd12bdc72','executor_v10_authority_ended_v2.py':'408060fd7867c2ad8d4eb956b18804a998472c1d2b2c17bfedca43f40daf81ee','cause_servo_interactive_v7.py':'8b04c9bfffd50ba0d5416977040d471962138559866558a87aeb5a3a20cd27b6','cause_servo_socket_v9.py':'4ab524fdb7f73b21e75313ef2f60ddcf6232bec0617a9b0d0a7480cb0cd229d7'}
for n,h in expected.items():
    got=hashlib.sha256((OUT/n).read_bytes()).hexdigest()
    if got!=h: raise SystemExit(f'candidate hash mismatch {n}: {got} != {h}')
print('PASS rebuild candidate')
