CLEAR='CLEAR_PROGRESS'
WATCH='UNCERTAIN_TRANSIENT'
HARD='HARD_INVALIDATION'
VOCAB=('ADVANCE','WATCH','YIELD')
MAP={CLEAR:'ADVANCE',WATCH:'WATCH',HARD:'YIELD'}

def select(state: str) -> str:
    return MAP[state]
