"""Independent reconstruction and observational-equivalence audit."""
from __future__ import annotations

import hashlib
import json
import math
import sys
from pathlib import Path


def cdf(value: float) -> float:
    if value < 0:
        e = math.exp(value)
        return e / (1 + e)
    return 1 / (1 + math.exp(-value))


def category_mass(cuts: list[float], eta: float) -> tuple[float, ...]:
    c = tuple(cdf(t - eta) for t in cuts)
    return (c[0], *(c[i] - c[i - 1] for i in range(1, len(c))), 1.0 - c[-1])


def loss(p: list[float], q: tuple[float, ...]) -> float:
    return sum(-x * math.log(y if y > 1e-300 else 1e-300) for x, y in zip(p, q))


def reconstruct(case: dict, spec: dict) -> dict:
    shifts, locations, residuals = {}, {}, {}
    for group, anchor_rows in case["anchors"].items():
        choices = []
        for idx in range(spec["shift_steps"] + 1):
            b = spec["shift_min"] + idx * spec["shift_step"]
            score = 0.0
            for row, level in zip(anchor_rows, spec["anchor_levels"]):
                score += loss(row["probabilities"], category_mass(spec["cutpoints"], level - b))
            choices.append((score, b))
        b = min(choices)[1]
        shifts[group] = b
        residuals[group] = max(
            abs(x - y)
            for row, level in zip(anchor_rows, spec["anchor_levels"])
            for x, y in zip(row["probabilities"], category_mass(spec["cutpoints"], level - b))
        )
        self_row = case["self"][group]
        locations[group] = min(
            (loss(self_row["probabilities"], category_mass(spec["cutpoints"], spec["self_min"] + i * spec["self_step"] - b)),
             spec["self_min"] + i * spec["self_step"])
            for i in range(spec["self_steps"] + 1)
        )[1]
    return {
        "case_id": case["case_id"],
        "threshold_shift_estimates": shifts,
        "self_location_estimates_conditional": locations,
        "contrast_conditional": locations["comparison"] - locations["reference"],
        "max_anchor_residuals": residuals,
        "model_fit_gate": "CONDITIONAL_FIT" if max(residuals.values()) <= spec["max_anchor_residual"] else "REJECT_MISFIT",
    }


def close(a: object, b: object, tol: float = 1e-10) -> bool:
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return abs(a - b) <= tol
    if isinstance(a, dict) and isinstance(b, dict):
        return a.keys() == b.keys() and all(close(a[k], b[k], tol) for k in a)
    if isinstance(a, list) and isinstance(b, list):
        return len(a) == len(b) and all(close(x, y, tol) for x, y in zip(a, b))
    return a == b


def candidate_matches(candidate: dict, expected: list[dict]) -> bool:
    if candidate.get("schema") != "8522-vignette-candidate-v1":
        return False
    if len(candidate.get("cases", [])) != len(expected):
        return False
    for want, got in zip(expected, candidate["cases"]):
        if not all(close(want[k], got.get(k)) for k in want):
            return False
        if got.get("calibrated_claim_permitted") is not False:
            return False
        if got.get("assumption_identification") != "NOT_TESTED_BY_OBSERVED_RATINGS":
            return False
    return True


def main() -> int:
    if len(sys.argv) != 5:
        raise SystemExit("usage: auditor.py candidate_input.json candidate.json oracle.json audit.json")
    obs_path, candidate_path, oracle_path, audit_path = map(Path, sys.argv[1:])
    data = json.loads(obs_path.read_text())
    candidate = json.loads(candidate_path.read_text())
    oracle_data = json.loads(oracle_path.read_text())
    expected = [reconstruct(case, data["spec"]) for case in data["cases"]]
    checks = []
    checks.append(("case_count", len(expected) == len(candidate["cases"])))
    for want, got in zip(expected, candidate["cases"]):
        checks.append((want["case_id"] + ":reconstruction", all(close(want[k], got.get(k)) for k in want)))
        checks.append((want["case_id"] + ":no_calibration_claim", got.get("calibrated_claim_permitted") is False))

    # The first case is generated by two distinct worlds; validate both parameterizations.
    truth = oracle_data["worlds"]
    observed = data["cases"][0]
    alias_checks = []
    for world in truth:
        predicted = {}
        for group, params in world["groups"].items():
            b = params["threshold_shift"]
            anchor_levels = params["anchor_levels"]
            predicted[group] = [category_mass(data["spec"]["cutpoints"], level - b) for level in anchor_levels]
            predicted[group].append(category_mass(data["spec"]["cutpoints"], params["self_location"] - b))
        actual = {g: [r["probabilities"] for r in observed["anchors"][g]] + [observed["self"][g]["probabilities"]]
                  for g in observed["anchors"]}
        alias_checks.append(all(close(predicted[g], actual[g]) for g in actual))
    checks.append(("both_truth_worlds_generate_same_observations", all(alias_checks)))
    observed_digest = hashlib.sha256(json.dumps(observed, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    checks.append(("observed_input_hash_matches_oracle", all(w["observed_input_sha256"] == observed_digest for w in truth)))
    checks.append(("distinct_world_contrasts", [w["true_contrast"] for w in truth] == [0.6, 0.0]))
    checks.append(("fixture_worlds_are_observationally_identical", truth[0]["observed_input_sha256"] == truth[1]["observed_input_sha256"]))
    checks.append(("nonuniform_violation_rejected", expected[1]["model_fit_gate"] == "REJECT_MISFIT"))
    checks.append(("conditional_positive_recovered", abs(expected[0]["contrast_conditional"] - truth[0]["true_contrast"]) <= 0.002))

    # Frozen corruption controls are applied to candidate/oracle copies and
    # must fail an independent equality or exact-world assertion.
    rejected = {}
    for name, mutate in {
        "invert_contrast": lambda c: c["cases"][0].update(
            contrast_conditional=-c["cases"][0]["contrast_conditional"]),
        "drop_comparison_group": lambda c: c["cases"][0]["threshold_shift_estimates"].pop("comparison", None),
        "force_misfit_accept": lambda c: c["cases"][1].update(model_fit_gate="CONDITIONAL_FIT"),
        "promote_calibrated_claim": lambda c: c["cases"][0].update(calibrated_claim_permitted=True),
    }.items():
        corrupted = json.loads(json.dumps(candidate))
        mutate(corrupted)
        rejected[name] = not candidate_matches(corrupted, expected)
    corrupted_oracle = json.loads(json.dumps(oracle_data))
    corrupted_oracle["worlds"][1]["true_contrast"] = truth[0]["true_contrast"]
    rejected["erase_distinct_alias_truth"] = (
        corrupted_oracle["worlds"][0]["true_contrast"] == 0.6
        and corrupted_oracle["worlds"][1]["true_contrast"] == 0.0
    ) is False
    checks.append(("all_mutations_detected", all(rejected.values())))

    report = {
        "schema": "8522-vignette-audit-v1",
        "disposition": "HOLD_NOT_IDENTIFIED" if all(ok for _, ok in checks) else "FAIL_AUDIT",
        "checks": [{"name": name, "pass": bool(ok)} for name, ok in checks],
        "check_count": len(checks),
        "error_count": sum(not ok for _, ok in checks),
        "truth_world_contrasts": [w["true_contrast"] for w in truth],
        "conditional_estimate": expected[0]["contrast_conditional"],
        "mutation_controls": rejected,
        "interpretation": "Ratings alone cannot distinguish the assumption-satisfied world from its uniform-vignette-shift alias.",
    }
    audit_path.write_text(json.dumps(report, sort_keys=True, separators=(",", ":")) + "\n")
    print(json.dumps({"disposition": report["disposition"], "check_count": len(checks), "error_count": report["error_count"]}, sort_keys=True))
    return 0 if report["error_count"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
