from pathlib import Path
import json,hashlib
root=Path(__file__).resolve().parent;errors=[]
def check(ok,name):
 if not ok:errors.append(name)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
f=json.loads((root/'fixture-input/fixture.json').read_text());check(sha(root/'fixture-input/save.png')==f['save_sha256'],'fixture save');check(sha(root/'fixture-input/source.png')==f['source_frame_sha256'],'fixture frame');check(sha(root/'fixture-input/freedoom2.wad')==f['iwad_sha256'],'fixture WAD')
a=json.loads((root/'initialize-01/argv.json').read_text());h=json.loads((root/'initialize-01/HOST.json').read_text());c=json.loads((root/'initialize-01/container-result.json').read_text());request=(root/'initialize-01/initialize.request.json').read_bytes();response=(root/'initialize-01/initialize.response.json').read_bytes();req=json.loads(request);res=json.loads(response);stream=[json.loads(x) for x in (root/'initialize-01/host.stdout.jsonl').read_text().splitlines()]
check(req['method']=='initialize' and req['id']==1,'initialize request');check(res in stream and res.get('id')==1 and 'result' in res and 'error' not in res,'host response stream');check(c['request_sha256']==hashlib.sha256(request).hexdigest() and c['response_sha256']==hashlib.sha256(response).hexdigest(),'container response byte custody');check(h['container_exit']==0 and h['host_exit']==0 and h['host_reader_alive'] is False and h['error'] is None and h['model_turns']==0,'terminal host/guest');check((root/'initialize-01/initialized.request.json').read_text()=='{"method":"initialized"}\n' and c['initialized_forwarded'] is True and h['initialized_sent'] is True,'initialized host forwarding receipt');check('--network' in a['container'] and a['container'][a['container'].index('--network')+1]=='none','network argument');check(sha(Path(a['cli'][0]))==a['cli_sha256'],'CLI identity');check(json.loads((root/'import-01/result.json').read_text())['version']=='1.3.0','native module import')
r={'scope':'post-run saved setup evidence check, not formal/recovery/interrupt audit','errors':errors,'passed':not errors,'provider_turns':0,'game_sessions':0,'input_emissions':0};(root/'SETUP_AUDIT.json').write_text(json.dumps(r,indent=2)+'\n');m={p.relative_to(root).as_posix():{'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(root.rglob('*')) if p.is_file() and p.name!='SETUP_FILES.json'};(root/'SETUP_FILES.json').write_text(json.dumps(m,indent=2)+'\n');print(json.dumps({'audit':r,'manifest_members':len(m)}));raise SystemExit(bool(errors))
