"""Preregister a posthoc full-frame versus action-region visual diagnostic."""
import hashlib,json,os
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE/'results/openttd-l-action-region-diagnostic-01';ARTIFACT=HERE/'results/openttd-l-action-region-01';RUN=HERE/'results/timing-envelope-openttd-l-02/fixed-astra'
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
ROOT.mkdir(parents=True,exist_ok=False)
full=RUN/'runtime/032.png';composite=ARTIFACT/'full-after-plus-action-region.png';prompt=ROOT/'prompt.txt'
prompt.write_text('''You are reviewing the visual outcome immediately after the first attempted OpenTTD road drag. The requested segment is exactly three connected ground tiles from A to B; B is the corner for a later second segment. Decide whether the visible road is aligned with those intended A-to-B ground tiles rather than a neighboring row. Use only the provided image. If the evidence is insufficient, choose uncertain. Return ONLY one JSON object: {"judgment":"correct|incorrect|uncertain","rationale":"1..400 characters"}. Do not propose actions and do not assume the operation succeeded merely because a cost appeared.\n''',encoding='utf-8')
plan={'study':'openttd-l-action-region-diagnostic-01','status':'PREREGISTERED_BEFORE_MODEL_CALLS','execution_order':['full-only','full-plus-action-region'],'model':'gpt-6-astra','effort':'medium','calls_per_condition':1,'same_prompt_sha256':sha(prompt),'conditions':{'full-only':{'image':str(full.relative_to(HERE.parent.parent)),'sha256':sha(full),'bytes':full.stat().st_size},'full-plus-action-region':{'image':str(composite.relative_to(HERE.parent.parent)),'sha256':sha(composite),'bytes':composite.stat().st_size}},'hidden_scoring_reference':{'expected_judgment':'incorrect','basis':'archived independent engine score: target 977/978 empty and surrounding 912..915 changed; never included in model prompt'},'sources':{name:sha(HERE/name) for name in ['preregister_action_region_diagnostic_v1.py','run_action_region_diagnostic_v1.py','model_pair_runner_v2.py','action_region_zoom_v1.py','audit_action_region_zoom_v1.py']},'decision_rule':'report whether each single call matches incorrect and compare reported input tokens; do not promote from this known-failure, fixed-order, one-call diagnostic','scope':'posthoc visual diagnosis only; no live action, causal estimate, reliability, latency or token-reduction claim'}
temporary=(ROOT/'preregistration.json.tmp');temporary.write_text(json.dumps(plan,indent=2)+'\n',encoding='utf-8');os.replace(temporary,ROOT/'preregistration.json');print(ROOT/'preregistration.json')
