from pathlib import Path
root=Path(__file__).resolve().parent
prep=(root/'prepare_sample_pair_01.py').read_text().replace('sample-pair-source-01','sample-pair-source-02').replace('sample_pair_entry_01','sample_pair_entry_02').replace('SAMPLE_PAIR_SOURCE_01','SAMPLE_PAIR_SOURCE_02')
(root/'prepare_sample_pair_02.py').write_text(prep)
probe=(root/'probe_sample_pair_01.py').read_text().replace('sample_pair_entry_01','sample_pair_entry_02').replace("'40124'","'40125'").replace("clock['runtime_ns']+2_000_000_000","clock['runtime_ns']+600_000_000").replace("terminal['status']=='completed'","terminal['status'] in ('completed','expired')").replace("result={'arm':arm,","result={'window_start_ns':clock['runtime_ns'],'window_end_ns':clock['runtime_ns']+600_000_000,'arm':arm,").replace('fixed commanded 600ms program; actual common scoring window defined by accepted emit_ns through +600ms','absolute clock response runtime_ns through +600ms; lease deadline equals scoring window end')
(root/'probe_sample_pair_02.py').write_text(probe)
driver=(root/'run_sample_pair_01.py').read_text().replace('sample-pair-01','sample-pair-02').replace('sample-pair-source-01','sample-pair-source-02').replace('sample_pair_01','sample_pair_02').replace('sample_pair_entry_01','sample_pair_entry_02').replace('SAMPLE_PAIR_SOURCE_01','SAMPLE_PAIR_SOURCE_02').replace('samplepair01','samplepair02').replace('sample-pair-construction-01','absolute-pair-construction-02')
driver=driver.replace("'D':'all six programs completed and normal child/reader closure; coast samples neutral and each pulse arm contains MOVE_RIGHT activity within accepted emit+600ms; otherwise FAIL/HOLD'","'D':'all six terminal completed or expired with verified empty release and normal child/reader closure; report samples within clock+600ms and late admissions/release separately; absent release or positive admission after deadline FAIL; no matched efficacy PASS' ")
driver=driver.replace('Sampled game input differs between neutral coast and bounded strafe pulses under fixed commanded duration','A common absolute lease deadline separates input release from delayed lifecycle completion despite synchronous snapshots').replace('600ms commanded duration; scorer-only samples; normal finish','600ms absolute runtime window and lease; scorer-only samples; completed or expired terminal then normal finish')
(root/'run_sample_pair_02.py').write_text(driver)
