import argparse,hashlib,json
from pathlib import Path
REQ=('actual_model_usage','fixed_11_equivalent_presentation','query_conditioned_model_return','continuation_overhead_measured','matched_task_source_model_session_cache','independent_correctness_value_endpoint')
def h(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--ledger',required=True);ap.add_argument('--source-map',required=True);ap.add_argument('--result',required=True);ap.add_argument('--freeze',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();o=Path(a.output);assert not o.exists();L=json.loads(Path(a.ledger).read_text());S=json.loads(Path(a.source_map).read_text());R=json.loads(Path(a.result).read_text());F=json.loads(Path(a.freeze).read_text())
    fam=L['families'];adm=[x['id'] for x in fam if all(x.get(k) is True for k in REQ)];model=sum(x.get('actual_model_usage') is True for x in fam);local=sum(x.get('local_query_latency_measured') is True for x in fam);hits=S['bounded_default_branch_searches']['query_temporal_observation']['result_count']+S['bounded_default_branch_searches']['MODEL_QUERYABLE_HISTORY']['result_count']
    checks={'decision':R['decision']=='PASS_RETAINED_TEMPORAL_BREAK_EVEN_NOT_IDENTIFIABLE_SCOPED','families':len(fam)>=5 and R['family_count']==len(fam),'model_family':model>=1 and R['actual_model_family_count']==model,'local_latency':local>=1 and R['local_query_latency_family_count']==local,'admissible_zero':adm==[] and R['admissible_rows']==[],'bounded_query_hits_zero':hits==0 and R['bounded_model_query_search_hits']==0,'no_causal_estimate':L['causal_cost_estimate'] is None and not R['causal_estimate_emitted'],'corruptions':all(R['corruption_controls'].values()),'formal':R['formal_invocations']==1 and R['reruns']==0 and R['replacements']==0 and R['tuning']==0,'source_plan':h('PLAN.md')==F['sha256']['PLAN.md'],'source_map':h('SOURCE_MAP.json')==F['sha256']['SOURCE_MAP.json'],'source_ledger':h('LEDGER.json')==F['sha256']['LEDGER.json'],'source_analyze':h('analyze.py')==F['sha256']['analyze.py'],'source_audit':h('audit.py')==F['sha256']['audit.py']}
    z={'status':'PASS' if all(checks.values()) else 'FAIL','checks':checks,'result_sha256':h(a.result),'freeze_sha256':h(a.freeze)};o.write_text(json.dumps(z,indent=2,sort_keys=True)+'\n');print(json.dumps(z,indent=2,sort_keys=True));raise SystemExit(0 if z['status']=='PASS' else 1)
if __name__=='__main__':main()
