from pathlib import Path
import subprocess,json,hashlib,time,shutil
root=Path(__file__).resolve().parent;source=root/'cancel-telemetry-source-01';live=source/'research/live_control';live.mkdir(parents=True,exist_ok=False)
for p in (root/'accepted-sink-source-01').glob('*.py'):shutil.copyfile(p,live/p.name)
candidate=Path('C:/Users/junny/Documents/Codex/2026-09-19/new-chat/work/calc-construction-publication-4d74/research/live_control/input_owner_cancel_telemetry_v1.py');shutil.copyfile(candidate,live/candidate.name)
payload=json.loads((root/'cancel_telemetry_test_payload_01.json').read_text());(live/'input_owner_v11.py').write_bytes(payload['v11'].encode());(live/'test_input_owner_v11.py').write_bytes(payload['v11test'].encode())
cause=source/'research/doom/results/cause';cause.mkdir(parents=True);(cause/'test_cancel_release_cause.py').write_bytes(payload['cause'].encode());shutil.copyfile(root/'cancel_telemetry_check_01.py',source/'check.py')
out=root/'cancel-telemetry-01';out.mkdir(exist_ok=False);image=(root/'image-02/image.id').read_text().strip()
args=['C:/Program Files/WSL/wslc.exe','run','--name','cancel-telemetry-59-4d74-01','--pull','never','--cpus','1','--memory','512M','--network','none','--user','65534','--env','HOME=/tmp','--env','PYTHONDONTWRITEBYTECODE=1','--env','OWNER_UNDER_TEST=/source/research/live_control/input_owner_cancel_telemetry_v1.py','--mount',f'type=bind,source={source},target=/source,readonly','--mount',f'type=bind,source={out},target=/out',image,'/usr/local/bin/python3','-B','/source/check.py']
(out/'FREEZE.json').write_text(json.dumps({'H':'Additive owner preserves five V11 telemetry contracts and cancellation dispatch/postIO cause handling.','T':'One eight-case existing-test construction, explicit candidate substitution, current99b7 causefixture and unchanged V11 cases; earlier support.','D':'All8pass; otherwise retainFAIL/STOP without rerun.','C':'Fake/mocked contracts, no actual backend/session/physical release.','U':'No Xserver/game/model/GPU, sourceRO/nonroot, requestedcaps enforcement unproven.','files':{p.relative_to(source).as_posix():{'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}for p in source.rglob('*')if p.is_file()},'image':image,'argv':args,'retries':0},indent=2)+'\n');start=time.monotonic()
with (out/'stdout.txt').open('wb')as so,(out/'stderr.txt').open('wb')as se:r=subprocess.run(args,stdout=so,stderr=se,timeout=45)
(out/'HOST.json').write_text(json.dumps({'exit':r.returncode,'elapsed_s':time.monotonic()-start},indent=2)+'\n');print((out/'stdout.txt').read_text());print((out/'stderr.txt').read_text())
