FROM sha256:18835dcb3335d1cc5367c78bf0c76a8174c522aebe0fd76ba743f509dcd4f309
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3-xlib && apt-get clean
ENTRYPOINT []
CMD []
