#!/usr/bin/env python3
"""Freeze the A09 source, retained task state, A04 crop set, and host."""
import hashlib,json,os,pathlib,platform,subprocess,sys
ROOT=pathlib.Path(__file__).resolve().parents[3]; PKG=pathlib.Path(__file__).resolve().parent
A04="research/analysis/pillow_focused_observation_payload_1998_t0_a04_20261009"; HERE="research/analysis/chromium_postsubmit_task_cue_1998_t0_a09_20261009"; FRAME="chromium-36563401256d"
def sha(b): return hashlib.sha256(b).hexdigest()
def main():
 designp=A04+"/design.json"; outputp=A04+"/results/candidate.stdout"; a04=json.loads((ROOT/outputp).read_text()); design=json.loads((ROOT/designp).read_text()); frame=next(x for x in design["frames"] if x["frame_id"]==FRAME); crops=[r for r in a04["rows"] if r["frame_id"]==FRAME and r["selected_kind"]=="FOCUSED_REGION"]; full=next(r for r in a04["rows"] if r["frame_id"]==FRAME and r["selected_kind"]=="FULL_FRAME")
 if frame["epoch"]!=8 or frame["first_action_id"]!="submit" or len(crops)!=20 or any(r["focus_payload_bytes"]>=full["full_payload_bytes"] for r in crops): raise SystemExit("A04 frame/crop preconditions failed")
 run="research/observation_gating/results/baseline-screen-02/chromium-1101-O0"; resultp=run+"/result.json"; submittedp=run+"/submitted.txt"; ledger=run+"/observations.jsonl"; actions=run+"/actions.json"; result=json.loads((ROOT/resultp).read_text()); submitted=(ROOT/submittedp).read_text()
 event=next(x for x in (json.loads(l) for l in (ROOT/ledger).read_text().splitlines()) if x["sequence"]==8); action=next(x for x in json.loads((ROOT/actions).read_text()) if x["action_id"]=="submit")
 if event["sha256"]!=frame["source_pixel_sha256"] or event["action_id"]!="submit" or action["public_effect_known_ns"]<=event["observed_ns"]: raise SystemExit("frame is not submit-before-public-effect state")
 if result["goal"]["token"]!="t001101" or result["oracle"]["actual"].get("value")!=["t001101"] or submitted.strip()!="value=t001101": raise SystemExit("task oracle mismatch")
 pilotp=HERE+"/preflight/full_frame.stdout"; pilot=(ROOT/pilotp).read_bytes()
 if b"t001101" in pilot: raise SystemExit("full-frame preflight is not an exact-token miss")
 tess=pathlib.Path(os.path.realpath("/run/current-system/sw/bin/tesseract")); tessdata=tess.parent.parent/"share/tessdata"; eng=tessdata/"eng.traineddata"; version=subprocess.run([str(tess),"--version"],stdout=subprocess.PIPE,stderr=subprocess.STDOUT,check=True).stdout.decode().splitlines()[0]
 paths=[designp,outputp,A04+"/FREEZE.json",A04+"/SHA256SUMS.txt",A04+"/results/audit.stdout",A04+"/REPORT.md",frame["source_png_path"],frame["ledger_path"],resultp,submittedp,actions,"research/observation_gating/gui_suite.py"]+[A04+"/"+r["focus_png_path"] for r in crops]+[HERE+"/"+n for n in ("README.md","PREFLIGHT.md","ENVIRONMENT.md","preflight/full_frame.stdout","preflight/full_frame.stderr","preflight/full_frame.exit","preflight/COMMAND.json")]
 inputs={p:sha((ROOT/p).read_bytes()) for p in sorted(paths)}
 codes={p:sha((PKG/p).read_bytes()) for p in ("candidate.py","auditor.py","formal_runner.py","freeze_sources.py","test_construction.py")}
 base=subprocess.run(["git","-C",str(ROOT),"rev-parse","origin/main"],stdout=subprocess.PIPE,check=True).stdout.decode().strip()
 f={"schema":"a09-freeze-v1","allocation":"LABEL-CONTROL-AMBIGUITY-1998-T0-A09-20261009","base_main_commit":base,"depends_on_a04_head":"5d4dbe50bb63a3df19f06b97701bde43217d24af","frame_id":FRAME,"epoch":8,"action_id":"submit","frame_png_path":frame["source_png_path"],"ledger_path":frame["ledger_path"],"ledger_sequence":frame["ledger_sequence"],"source_pixel_sha256":frame["source_pixel_sha256"],"actions_path":actions,"result_json_path":resultp,"submitted_path":submittedp,"a04_package":A04,"a04_design_path":designp,"a04_candidate_path":outputp,"target_token":"t001101","submitted_expected":"value=t001101","full_payload_bytes":full["full_payload_bytes"],"pilot_stdout_path":"preflight/full_frame.stdout","pilot_stdout_sha256":sha(pilot),"tesseract_path":str(tess),"tesseract_sha256":sha(tess.read_bytes()),"tesseract_version":version,"tessdata_dir":str(tessdata),"eng_traineddata_path":str(eng),"eng_traineddata_sha256":sha(eng.read_bytes()),"psm":11,"python_executable":os.path.realpath(sys.executable),"python_version":sys.version,"platform":platform.platform(),"machine":platform.machine(),"kernel_release":platform.release(),"candidate_invocations":1,"auditor_invocations":1,"crop_ocr_invocations":20,"retries":0,"inputs":inputs,"code_sources":codes,"scope":"one retained Chromium submit-before-public-effect frame and exact token Tesseract extractability only"}
 b=(json.dumps(f,sort_keys=True,indent=2)+"\n").encode(); (PKG/"FREEZE.json").write_bytes(b); (PKG/"FREEZE.sha256").write_text(sha(b)+"  FREEZE.json\n"); print(json.dumps({"freeze_sha256":sha(b),"input_count":len(inputs),"crop_count":len(crops),"code_count":len(codes),"base_main_commit":base},sort_keys=True))
if __name__=="__main__": main()
